name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger the workflow when a tag starting with 'v' is pushed (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Deno
      uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31
      with:
        deno-version: 'v2.0.6'  # specify the version of Deno you want to use
    
    - name: Install modulesdsafdasf
      run: deno install

    - name: Make shell script executable
      run: chmod +x ./buildall.sh

    - name: Run buildall.sh
      run: ./buildall.sh

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: compressed-files
        path: build/compressed/*  # Upload the files in the build/compressed directory

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/compressed/*  # Upload the files to the GitHub release
        tag_name: ${{ github.ref }}  # Use the pushed tag as the release version
        release_name: Release ${{ github.ref }}
        body: "Automated release for version ${{ github.ref }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the personal access token here

